const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    FETCH_FILTERED_COLLECTION: 'FETCH_FILTERED_COLLECTION',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    TOGGLE_FILTER_MENU: 'TOGGLE_FILTER_MENU',
    TOGGLE_SORT_BY_DROPDOWN: 'TOGGLE_SORT_BY_DROPDOWN',
    FILTER_COLLECTION_BY_PRICE: 'FILTER_COLLECTION_BY_PRICE'
 }

export default ShopActionTypes