const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    TOGGLE_FILTER_MENU: 'TOGGLE_FILTER_MENU',
    TOGGLE_SORT_BY_DROPDOWN: 'TOGGLE_SORT_BY_DROPDOWN',
    FETCH_COLLECTION_DESCENDING: 'FETCH_COLLECTION_DESCENDING',
    FETCH_COLLECTION_ASCENDING: 'FETCH_COLLECTION_ASCENDING'
 }

export default ShopActionTypes